### ISSUE TITLE
No validation on input fields

### ISSUE THREAD

**Issue by Yutika-Nemade** [Yutika-Nemade/Enrollment-Form#1]
**Describe the bug**
There is no validation on input fields such email, name. Any email should contain @ symbol and name can't contain numbers.

**To reproduce**
1. Go to Page.
2. Fill the data in input fields.
3. Click the enroll student.
4. It will directly add the information without validating it.

**Expected behavior**
Add validations to validate the data in input fields.

**Screenshots**
![image](https://github.com/Yutika-Nemade/Enrollment-Form/assets/109644250/67afd600-ae48-4c56-8109-643fafe2ce73)

**Comment by bilalshaikh292** [comment]
heyy is the issue open i would like to contribure ?
